#FROM image-registry.openshift-image-registry.svc:5000/openshift/php@sha256:836494d2d6c89b08aee678c0a35bb31b1c7003b190aee4ea30bf04fb4d3a8ff3
FROM httpd

USER root

# By default, listen on port 8081
EXPOSE 8080/tcp